image_finetune: false

output_dir: "outputs"
pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"
dreambooth_path: ""

unet_additional_kwargs:
  use_inflated_groupnorm         : true
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  motion_module_mid_block        : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "dataset/illustration/style_dataset.csv"
  video_folder:    "dataset/illustration/split"
  sample_size:     256
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "illustration style, two boys sitting on the sofa and eating apples."
  num_inference_steps: 25
  guidance_scale: 8

trainable_modules:
  - "none"

unet_checkpoint_path: ""

learning_rate:    1.e-4
scale_lr:         false
lr_warmup_steps:  20
lr_scheduler:     "cosine"

train_batch_size: 1
num_workers:      0

motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"
motion_module_pe_multiplier: 1

train_lora: true
lora_rank:  32
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules: ["to_q", "to_k", "to_v"]

max_train_epoch:      -1
max_train_steps:      1000
checkpointing_epochs: -1
checkpointing_steps:  600

validation_steps:       200
validation_steps_tuple: [100]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: true

is_debug: False
